### ISSUE TITLE
Занятие 3.

### ISSUE THREAD

**Issue by stsdmchv** [Chelik-404/Bondarenkov#7]
Задача 2 - учесть случай когда a = b
Задача 10 - работает не правильно

**Comment by Chelik-404** [comment]
Вторую задачу я исправил, а 10 правильно работала, просто вы не те числа вписывали.
Что бы решить задание нужно найти сумму чисел Фибоначчи в промежутке чисел, границы этого промежутка записываются в переменные "n" и "k", а вы записывали кол-во чисел после определённого числа. А в задание написано что нужны границы, поэтому я изменил вывод, чтобы было понятнее какие числа, куда нужно записывать.

**Comment by stsdmchv** [comment]
Если я вписываю числа и у меня выводит не верный ответ, то это значит что не я вписываю неправильные числа, а что задача решена не верно.
"Пользователь вводит два числа N и K с клавиатуры. N - количество чисел из ряда Фибоначчи, K - порядковый номер в ряду, с которого нужно начать. Посчитайте сумму этих чисел. В решении этой задачи можно использовать только один цикл." - в условии задачи про границы ничего не сказано.

**Comment by stsdmchv** [comment]
В задаче конкретно сказано: K - порядковый номер в ряду, с которого нужно начать, N - количество чисел из ряда Фибоначчи. Пользователь не должен считать на котором числе ему нужно остановиться

**Comment by Chelik-404** [comment]
Здравствуйте, я переделал 10 задачу, теперь она подходит под условие(просто с начала я подумал что мы берем количество чисел как правую границу).
И вы не исправили мне оценку за 2 задачу
